# -*- coding: utf-8 -*-
"""DL_5.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KGBAq9L0nLSGatl100T01sWK2-ALW3u5
"""

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from keras.datasets import mnist
from sklearn.metrics import mean_squared_error
import numpy as np
(trainX, trainy), (testX, testy) = mnist.load_data()
nsamples, nx, ny = trainX.shape
d2_trainX = trainX.reshape((nsamples,nx*ny))
pca = PCA(n_components=2)
pca_data = pca.fit_transform(d2_trainX)
print("shape of reduced data is", pca_data.shape)
data_hat=pca.inverse_transform(pca_data)
error=np.sqrt(mean_squared_error(d2_trainX, data_hat))
print(error)

plt.figure(figsize=(10,10)) 
plt.scatter(pca_data[:,0], pca_data[:, 1], s = 100,marker='<' ,c = 'red')
plt.title('PCA on MNIST dataset')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.show()
